version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: order-pipeline-postgres
    environment:
      POSTGRES_DB: order_pipeline
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  localstack:
    image: localstack/localstack:3.0
    container_name: order-pipeline-localstack
    environment:
      SERVICES: s3,lambda,dynamodb,sqs,iam,cloudformation
      DEBUG: 1
      DEFAULT_REGION: eu-west-2
    ports:
      - "4566:4566"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - localstack_data:/var/lib/localstack
      - ./aws_setup.sh:/docker-entrypoint-initdb.d/aws_setup.sh
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 10s
      timeout: 10s
      retries: 5

volumes:
  postgres_data:
  localstack_data: